# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updates',
            new_name='Update',
        ),
    ]
