# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('datum', models.FloatField(default=-1)),
            ],
            options={
                'ordering': ('-created',),
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='data',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='uid',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='kind',
            field=models.CharField(choices=[('TEMP', 'Temperature'), ('PRES', 'Pressure'), ('REED', 'Reed'), ('BATT', 'Batter')], max_length=255),
        ),
        migrations.DeleteModel(
            name='Datum',
        ),
        migrations.AddField(
            model_name='rawdata',
            name='sensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rawdata', to='sensors.Sensor'),
        ),
    ]
