# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='created',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
    ]
