# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170509_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawdata',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
