# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 05:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_auto_20170509_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='uid',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
